---
- name: Install Postgresql server and client
  become: yes
  apt: pkg={{ item }}-{{ postgresql.version }} state=present update-cache=yes
  register: postgresql_install
  with_items:
    - postgresql
  tags:
    - packages

- name: Install development header files
  apt: pkg={{ item }} state=present update-cache=yes
  become: yes
  when: postgresql.install_development_headers == true
  with_items:
    - libpq-dev
  tags:
    - packages

- name: Install PostgreSQL config file
  become: yes
  template: src=postgresql.conf
            dest=/etc/postgresql/{{ postgresql.version }}/main/postgresql.conf
            owner={{ postgresql.user }} group={{ postgresql.group }}
  notify:
    - restart postgresql
  tags:
    - configuration
