language: python
dist: bionic

services:
  - docker

#env:
#  global:
#    -DOCKER_REPO=dock101/travis-docker-python

before_script:
  - echo "Testing Docker Hub credentials"
  - if [[echo "$DOCKER_PASSWORD" | docker login -u=$DOCKER_USERNAME --password-stdin ]];then echo "Docker Hub credentials are working"; else echo "Login failed"; fi

script:
  - docker ps -a

after_script:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - if [[ "$TRAVIS_BRANCH" == "main" ]]; then echo -e "Push image to Docker Hub"; fi
  - echo "$DOCKER_PASSWORD" | docker login -u=$DOCKER_USERNAME --password-stdin
  - export REPO=${DOCKER_USERNAME}/travis-docker-python
  - echo "$REPO"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "main" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo "$TAG"
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker tag ${REPO}:${TAG} ${REPO}:${COMMIT}
  - docker tag {$REPO}:${COMMIT} ${REPO}:travis-${TRAVIS_BUILD_NUMBER}
  - docker push $REPO
  - docker run --rm -ti ${REPO}:${TAG}
  - docker ps -a
