language: python
#python:
#  - 3.6
#  - 3.7
#  - 3.8
dist: bionic
os: linux
services:
- docker
- xvfb
#- postgresql
#- rabbitmq
env:
  global:
#  - PRIV_REPO=travis_docker_pyhton_private
  - REMOTE_REPO=travis-docker-python
  - REG=${DOCKER_USERNAME}/${REMOTE_REPO}
  - PYPI_USER=${PYPI_USERNAME}
#  - MAKE_TARGET=test
  - TAG=`if [ "$TRAVIS_BRANCH" == "main" ]; then echo "latest"; else echo $TRAVIS_BRANCH;fi`
  - secure: misxC3oVqAAWMZxpVE4GR2Jspp/uLvpnCgKiwhMCmiDHr9bdpcU5TdzlvBp91DXHLmA6doNZ2+Uo57kK8RlLm4zQWlQ+hyJilv7SUcR1DTN9qGZVynD012k2Yb3HS0h5OVoSTXuX2o3cF8Szr92MgPEte1+GnaML8TqOhKZluRvloQTZlmKTuqCX0mT2ezjOqRBI9+MjjxxxzEU81N0DVQbp9yEJsD9iS1vc/iqs0mXC8eiwDz7j2SPomr2eo2KiAg82QOtZvppaoHmzYU0b2N4low5dngfTh54JOJNl31Ovl1TyQRF8u5Y6LlWc9EAWGBXcPOpj1IPFbkuP5blaEjXtEuzunqN/J0LXzOvNMNFhEqdgV7AgxEl5mxP4yLpmRSQCUcMxy6md8fP2zUVp9ksytbi+FEpysucAedokUEMZu0kQMrsvSIZFnkcvIUXwpIrWLk+6CoOYazdV0DHFpGWm42BF+RqJZSOea8gmWpG3oeIiLvZGausbf3W0c+VEncCYsQS+tx+zhspjjqvKaIfssull7Dh40/5iXdRpoVVKmuJaejNxN3epXosM/yyBmN2bIrRLfQRJbZiar1xXRySZQQGvpDCm+rqDEww9rDIWsM2EoyCBGadyRfnV+LWb1jRtmuuqUtIzCb2gJZ2EgsErgrpsCyy9uY826ujGv+E=
  - secure: nIEbAlc/uvHrPNyXQtec7QyUGMTv27PwupDPmO9NS9T2qmSa+4U8sBPHCDADYXBPPIqc4wGaWavPm6wO3qBGkdu0ncanv1ffvFSC20bEvMIgUR2+BW8b0V573+3+1YjEK9zYeA0fEVGrY8VNZFABzj4cQuKAOtT0GmqhBYxEuEPhd468+omJj5yzp725miW1xN/zq0LlRchVPITLDeP9xKdfVVH9iXeD7i6aXlUrL+xObcG9FwRZZo7+eeKox/J3/6DumM4xJQyODQwmGdZIxNUa2/3p9A2imIJs5u3IPW0L8FnZSmmCXDcr7nuie/yKdXil1GydpxSLEaPjR+he4MpuK40clme9Mo0UgmYGhvnQ/jaLW6TMP/MvRN46LBIYKGJOVUVvbSYJ2x/+8ULmPoqql9cvmfbpy0i36WVDOWweUaj4ryceckhF9XS7pY+bncOehZw0qz2uDpV0ljvku8eVPgvKYXVGZCgY4KcQWkXrDglnu0hwuF8tz/cigQVrDOmhaw9AwQn/PuNkSVqs/2PuBZvEb1R2rECZGRiiWePeOZFW12fqPDV7IArqpeJW0wCnDHhmxfnuy0WvD05oA17VNmcVAorqh3U3cIjTDDtItFJFnoyfEDWNigSczTGmTRzQTwMNCK00mPhtzM9FPusQ4N1Jdp7c/1c50UucEAE=

#before_install:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
#  - pip install .
#  - pip install nose coverage
  - pip install coveralls
  - pip install ansible
#  - pip install x11vnc
#  - pip install xvfb
#  - pip install fluxbox
#  - pip install docker-py

#script: if [[ -n "$MAKE_TARGET" ]]; then echo "$MAKE_TARGET"; else tox; fi
#before_script:
#  - psql -c 'create database travis_ci_test;' -U postgres
#after_success:
#- echo "$DOCKER_PASSWORD" | docker login -u=$DOCKER_USERNAME --password-stdin
#  grep "Login successful"==Login successful ; then echo "Login successfull"; else
#  echo "Login Failed"; fi
#cache:
#  directories:
#    - $HOME/.cache/pip
stages:
- Build
- Test
- Coverage
- Deploy
jobs:
  include:
  - stage: Build
    name: Check Docker Login creds
    script:
#    - export DISPLAY=${DISPLAY:-:0} # Select screen 0 by default.
#    - xdpyinfo
#    - pgrep -a Xvfb && Xvfb $DISPLAY -screen 0 1024x7fluxbox 2>/dev/null & fi68x16 & sleep 1
#    - if which fluxbox &>/dev/null; then ! pgrep -a fluxbox &&
    - echo "IP:$(hostname -I) ($(hostname))"
    - echo "Testing Docker Hub credentials"
    - echo "$DOCKER_PASSWORD" | docker login -u=$DOCKER_USERNAME --password-stdin
    - echo "Docker Hub credentials are working"
    - echo ${REMOTE_REPO}
    - echo ${DOCKER_USERNAME}
    - docker build -f Dockerfile -t $REG:${TRAVIS_COMMIT} .
    - docker images
    - docker tag $REG:${TRAVIS_COMMIT} $REMOTE_REPO:latest
    - docker tag $REG:${TRAVIS_COMMIT} $REG:travis-${TRAVIS_BUILD_NUMBER}
    - docker push $REG:travis-${TRAVIS_BUILD_NUMBER}
#    - docker run $REG:travis-${TRAVIS_BUILD_NUMBER} cat hello.txt
  - stage: Test
    name: Test Code
    script:
      # # command to run tests, e.g. python setup.py test
      - tox
      - docker run $REG:travis-${TRAVIS_BUILD_NUMBER} cat hello.txt
#    - find ./ | sed -e 's/[^-][^\/]*\//--/g;s/--/ |-/'
#    - echo -e "\n\n\n\n"find . -type f -exec cat {} +
#    - find . -type f -exec cat {} +
      - docker ps -a
      - ansible --version
#    - cat /home/travis/virtualenv/python3.6.10/etc/ansible/ansible.cfg
#    - sudo apt-get update -y
#    - sudo apt-get install software-properties-common -y
      - ansible-playbook -i tests/hosts setup.yml
#      - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
#      - curl -k https://localhost:6432
      - netstat -ln | grep 5432
      - sudo netstat -tulpn
#      - sudo curl -v 'https://localhost:5432'
  - stage: Coverage
    name: Coveralls
    after_success:
    - coveralls
    script: echo "Coverage report sent"
  - stage: Deploy
    name: Deploy package to pypi
    deploy:
      provider: pypi
      username: ${PYPI_USER}
      password: ${PYPI_PASSWORD}
#        secure: HIRkiwkjX434tZfY42UdLQwfPfloXaBii4k9eCsRLr4y1q7YXv+BH1W3ZPDFpRg220YukiCO/smhFBvhSf6XxCb+XX2cLLQbLB/GxTBFchiuVMlpXv7td/jJL3zCxDKotEEvNcaf+VzmWb4Q9RXr6R8cBuMAy1n14siX6HLNw5A89qj5jV2yXeQ/aYCh4rPDwWvZP5C7AVT84uHS+j1jO4DnF+Rt9f8NCJU7rowfLP7DVQ6TAg+/BasFGGmc1zO/BUr4FP1vqQvJ5sEF73vC0W0Nk0fv+0nl4bxOJXFm4gDA7o8VY9RlRLljuhxgJ8GUgBykMdB6GNQPjrL7FzUkqBD7HAuVlAsL6fbVXWSYYYwyT4yxrbk8N6IWJdLyaDEDZAuvvye62FqIGkKCMJawHmv2JA7mdD888gRe2BMyQ7rYVJNVtbiSvr2wZIh6AS0fJibchUM3kRh3Glnt50Bh+D4vaYQ9BFFsIdeRPUVmLVIYOuVujxUTFzARIw68XwN6X7pG4WrRMuuMmcj3aWFIi4JS+ZHBVF7TtqfSMHyDP9udmWmKOM2JKiqS/gNnKVI/F46a10Bv7OyVBcFlxQpX7ded/JJJ+AZyMq8epkM/CFv9y29aaiROS3uk0ctQo/MMEyYqiqXgdcyGrxSqfniaetSLSm7gY8s9DIbowuu77oc=
#      skip_cleanup: true
      skip_existing: true
      on:
        branch: main
        repo: $GITHUB_ACCOUNT/$REMOTE_REPO
    script: echo -e "$PYPI_USER"
notifications:
  slack:
    rooms:
    - secure: GL9vu5zxVrNzq2phF8sILZZ3UoHHsch0I8YrXuCyD6VXaxaCkzk/CkxOLxlyerkfSDB1KfknqavOrV5vfdQeZMculTWQDbwpo8E+x/ENMMCiYFNHk0yg0HUYres1FLIYka/P4qszW0Op5DkkDVZpZgUOYvlt3x2auB68qh9za8+RXM3fd83lUNoNpSeO8rdqckADCfu+xs6rMODh3dN1k8J4Cf79WeBnb/br9x0vT26H08+0XoOjcbqtQnSqzaLPpK/jwvx74wan+kcfF0ghHRG7Ee/dpPMUAOgHMSt9jlsmYvctq3XZGqERRjTpoHH1jjTzZ3PZt6aK7og/n62ZvgXC01Z1fE0rRisvFJlipyIjQuzNlTxJGxK09SqufUdB2X+u4QzseT7n2a2l7cQiuu02vb7dMVY+OB9bjQ8XHowdArcbrAzojD0zsbgj4leXILb7iZw+1VTU7OI3yr3/+guGtfkgz7GpcaU5553TRFAO/XLtfoJToRxLvhUoeR/qOf2WejnfpDLWS69zMvPRKrZqIPyAOsvmTKzAUQB7EG9zKfyeqzGnlZKeU8qP061OttvYWdbsUL/4a89NbCrIjmX/c6IFTU7CdAUTtRZ1ZryQbYNAWMccMJ3EXHO3lxF15auCHQjha6tyJrcxpkCbLtNW+jA9/64VQCH2EBdsy2Q=
    template:
    - "%{repository_slug} (%{commit}) : %{message}"
    - 'Build details: %{build_url}'
    on_success: always
    on_failure: always
