language: python
dist: bionic

services:
  - docker

env:
  global:
    - REPO=travis-docker-python
    - REG={DOCKER_USERNAME}/{REPO}
    - TAG=`if [ "$TRAVIS_BRANCH" == "main" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

before_install:
  - echo "Testing Docker Hub credentials"
  - if [[echo "$DOCKER_PASSWORD" | docker login -u=$DOCKER_USERNAME --password-stdin ]];then echo "Docker Hub credentials are working"; else echo "Login failed"; fi
  - docker build -t ${REPO}_image .

script:
  - echo "\n\n Hello \n\n"

#deploy:
#  provider: script
#  script: bash docker_push.sh
#  on:
#    branch: master

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - if [[ "$TRAVIS_BRANCH" == "main" ]]; then echo -e "Push image to Docker Hub"; fi
  - echo "$DOCKER_PASSWORD" | docker login -u=$DOCKER_USERNAME --password-stdin
#  - export REPO=${DOCKER_USERNAME}/travis-docker-python
  - echo "$REPO"
#  - export TAG=`if [ "$TRAVIS_BRANCH" == "main" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo "$TAG"
  - docker build -f Dockerfile -t $REG:$COMMIT .
  - docker tag ${REG}:${COMMIT} ${REG}:${TAG}
  - docker tag {$REG}:${COMMIT} ${REG}:travis-${TRAVIS_BUILD_NUMBER}
  - docker push $REG
  - docker run --rm -ti ${REG}:${TAG}
  - docker ps -a
