language: python
dist: bionic
os: linux

services:
- docker

env:
  global:
  - REPO=${REPOSITORY_1}
  - REMOTE_REPO=${REPOAITORY_2}
  - REG=${DOCKER_USERNAME}/${REPOAITORY_2}
  - TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - secure: c+0SaNnJlfjSQzfUZtg3RVwl64YGVvulwjgeAuozNyXQ2tcaLpakJzSqKCq+ovnkWfQFYKK3KntWkPd5j49cvYL+dglbvnJWrkW81UbLCvi2lI3q3980PgdZ4GY2sQgORcHzGEp5FqBgwJXSIcaQSfQZPg5Bc0D13t+LKNbdv9SFRsv88IPkXWg+FQxm16RFJorpXZQmqRaQCUCHYuYyJbL+tZxWkzDQAblri0B2mfy+ZTKd1yMVKCaele1tak622b7qbI30/yVV3mJmLBiDX2ENk+Cz8dWfSVNQXLHSGrMeDfj2dZFVbsicURTI6VVrADBFdmjJAmaCIwcCJFawv2AsRBEzeN3P1nsiU9uGWoBpN4u2Vu8/ZxdSd6BbvDEHuNC99EsGvBlaXovauOM+x8CkgwX6dxE1YImB/tZ3P0OcJ75TV42DrDgWp0ydr5R4BvP2MjJ/OJ0/uRNqmrQidPPfQc/2VVyFQ+HQ7wdZ/898LSmXm93Hn3zIIHpkQkEYZK7WkXMVDaXzs/nO5cd13HvYUaOn9eFERfAT7D08lsHvU7PfvBfrnUshk58rFaoC2C/OXicYsoCsSChUAe+VQ7Hbr0+VDZVZC7LDwJltLx2BY0nw88sq+dJr5fHDQQK32M6xTx7uMHOXTFNloROsnyNNNjFQcnP31ZZQowS0Pn8=

before_install:
- echo "Testing Docker Hub credentials"
- echo "${DOCKER_PASSWORD}" | docker login -u=${DOCKER_USERNAME} --password-stdin
- echo "Docker Hub credentials are working"
- docker build -t '${DOCKER_USERNAME}/${REPOAITORY_2}' .

script:
- echo -e "\n\n Hello \n\n"

after_success:
- echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
- if [[ "${TRAVIS_BRANCH}" == "master" ]]; then echo -e "Push image to Docker Hub"; else echo -e "Cannot push to Docker Hub due to non-master active branch"; fi
- echo "${DOCKER_PASSWORD}" | docker login -u=${DOCKER_USERNAME} --password-stdin
- echo "${REPO}"
- echo "${TAG}"
- echo "${REG}"
- docker build -f Dockerfile -t -e  ${REG}:${TRAVIS_COMMIT} .
- docker tag "${REG}":"${TRAVIS_COMMIT}" "${REMOTE_REPO}:latest"
- docker tag "${REG}":"${TRAVIS_COMMIT}" "${REG}":travis-"${TRAVIS_BUILD_NUMBER}"
- docker push "${REG}":travis-"${TRAVIS_BUILD_NUMBER}"
- docker run -ti "${REG}":latest
- docker ps -a

notifications:
  slack:
    rooms:
      - secure: dOA/3Ok64FV4SwEC4E3hbChf9bqUQZUCbZs5pvXDl6v+iT5TZCyhJhg355jOK/+jMTMdG5MO024sFjpgAnvMLu51cMyK8ywqYfDBBaNlENCMoXOWVknRiIYl7KgooXcibMMH+1izUynqy+9QUruWLRFOCIeOUC69VnSTAm8+gG6MAhe9khbHc7FdYvhqWM4fJ4WWpmrFwp1QRRCXxdx0B8C+WORa5zcnRUOMIqoieQ84i+4yt/V7lU+w5B5pXZhfgdmumxhvevuIY7E0Q6Ry07wnkdvlcD5NY/4T0hs1Ac78IIld+2mQ7/v4IC+/PCZt8rI0pm+uUWZPXagX3xuxg93XKRnKnmaj5A2orUZ8heoo1Hz34doYxBV3FebZ6Qyfx/oLTQQyyzOfY5Xk29M27bh2D3cpTjZDIJHKkdn4Xzyn6RXmuqp0H3coDhg7smNIHBeyGPTcdmbj5atnslrJGZsbZa7r5tDKzlLk2zSuywKC9iPmAtqmJVCqYNNp6n+LPtMHk+0t1WfOuvspJVh3MF0XHhjTpCk0/B4xE8ZwJr8g6qwcH54WAwKK0eKj4z7HZuhA3bc1igGd+0gubf4PAbclKSlDtvcCjtpLl4LoE69rUGragpPNq9WVzQZN7KibvlMFvWHOWRhXY1K/nlU3t90AbvRP2O//nDnyozpyGBE=

    template:
      - "%{repository_slug} (%{commit}) : %{message}"
      - "Build details: %{build_url}"
    on_success: always # default: always
    on_failure: always # default: always
