language: python
dist: bionic
os: linux

services:
  - docker

env:
  global:
    - REPO=travis-docker-python
    - REG=${DOCKER_USERNAME}/${REPO}
    - TAG=`if [ "$TRAVIS_BRANCH" == "main" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

before_install:
  - echo "Testing Docker Hub credentials"
  - docker build -t ${REPO} .

script:
  - echo -e "\n\n Hello \n\n"

#deploy:
#  provider: script
#  script: bash docker_push.sh
#  on:
#    branch: master

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - if [[ "${TRAVIS_BRANCH}" == "main" ]]; then echo -e "Push image to Docker Hub"; fi
  - echo "${DOCKER_PASSWORD}" | docker login -u=${DOCKER_USERNAME} --password-stdin
#  - export REPO=${DOCKER_USERNAME}/travis-docker-python
  - echo "${REPO}"
#  - export TAG=`if [ "$TRAVIS_BRANCH" == "main" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo "${TAG}"
  - echo "${REG}"
  - docker build -f Dockerfile -t travis-docker-image-python:latest .
  - docker tag travis-docker-image-python:latest travis-docker-image-python:v1
  - docker tag travis-docker-image-python:latest travis-docker-image-python:travis-${TRAVIS_BUILD_NUMBER}
  - docker push travis-docker-image-python:travis-${TRAVIS_BUILD_NUMBER}
  - docker run -ti travis-docker-image-python:travis-${TRAVIS_BUILD_NUMBER}
  - docker ps -a
